application: tuvero-issue
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /
  script: main.application
  secure: optional

- url: /settings
  script: main.application
  login: admin
  secure: always

- url: /css/(.+\.css)
  static_files: css/\1
  upload: css/(.+\.css)
