application: boulesdb
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /
  script: boulesdb.application
  login: admin
  secure: optional

- url: /.*
  script: boulesdb.application
  secure: optional
